services:
  - redis
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest-cov
  - pip install codecov
install:
  - pip install ".[test]"
script:
  - pytest
after_success:
  - codecov
env:
  global:
    secure: "WOjQG9V6gUb7bTvi/DnPFN4lIDtgzeuVQCWE4Jem65FyktNlp55wUaK+nBHmShID81sDWjJY/2/Zl+fLE7wYj+XFdSWb/EteoL/vmYJXdT3KbekkhJSk12kNAUlWWpWVgVtH9JrFlhwE7pQyELKYNYsbNrjV7xDCQ8WxrmohAfxzxcF/bUxXFd8X/boRGsX/f5y0ZzV+ygpOWL5kG+9wOLI6Tktni/Axn4F2/UlX9hgmyXf3eXYus596BkoEZUApqVoeqC7LBv+YZ6RGN0YhE4zrt1iGSX5nAp6xsyRODaQpXTEwC8maY4dyhi/shvZ3jzMjz8JuN6y0wdk+YX2mkxfAXw8CRBRklVWT4Ii7MwPJysFXLHIh+++fK//vZo2yPS5XJu40+1aDMgb+GQaQRuZvnvdaq0rh4qhUDwIvgF7BqMvhyvSQpclBO0TO3y1IWtr6nISET1l13h88X0DPn799HHEFsy8vUe5QRdBbz2j2TgMgdBwGX8w+eNm/t1Eondo70bHQS3axDIfOExCPex/62LATvKVdMIBUZQMrIuZ8L1HqCLOXXMOS4qXcTSIkJEmaqWiAgCBQISkcpEz5IeHeK5X9THlCne+GSrS4XFjAa5QYqjiavUAVe5kIURQ5jGEM/GJgqb9uaXyAiNtAwe0pESSweps6prYMChek+pk="
