name: RedisPal-CI

on:
  push:
    branches:
      - "master"
    tags:
      - "*"
  pull_request:

jobs:
  before:
    name: Check for dependency installation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"
          architecture: "x64"
      - name: Install dependencies
        run: pip install poetry && poetry install

  tests:
    needs: before
    name: ${{ matrix.os }}${{ matrix.arch }} - Python ${{ matrix.python-version }} - Redis ${{ matrix.redis-version }} - tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x64]
        python-version: ["3.6.x", "3.7.x", "3.8.x", "3.9.x"]
        redis-version: [4, 5, 6]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}
      - name: Set up Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Install dependencies
        run: pip install poetry && poetry install
      - name: Run tests
        run: |
          poetry run pytest

  build_and_publish:
    needs: tests
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to PyPI
        uses: JRubics/poetry-publish@v1.10
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
